version: '3.4'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    env_file: .env
    volumes:
      - ./init-script.sh:/docker-entrypoint-initdb.d/init-script.sh
      - /var/lib/docker_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    shm_size: '128mb'
    restart: always
